version: 3.2-{branch}-{build}
branches:
  only:
    - dev

configuration:
- Release

platform:
- x64

os: Visual Studio 2015
clone_folder: C:\devel-src\roboptim-core-plugin-eigen
environment:
  CI_OS_NAME: win32
  CI_TOOL: appveyor
# Dependencies should be a list of dependencies separated by spaces
  CHOCO_DEPENDENCIES: "doxygen.portable"
  GIT_DEPENDENCIES: "gergondet/ltdl-win32 roboptim/roboptim-core#dev"
# Should be the same as clone_folder
  PROJECT_SOURCE_DIR: C:\devel-src\roboptim-core-plugin-eigen
# Do not tinker with the variables below unless you know what you are doing
  SOURCE_FOLDER: C:\devel-src
  CMAKE_INSTALL_PREFIX: C:/devel
  CMAKE_BUILD_TYPE: Release
  PATH: C:/devel/bin;C:\Libraries\boost_1_60_0\lib64-msvc-14.0;C:\msys64\mingw64\bin;%PATH%
  PKG_CONFIG_PATH: C:/devel/lib/pkgconfig
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0
  MINGW_GFORTRAN: C:\msys64\mingw64\bin\gfortran.exe
# N.B: empty lines here and in test_script are VERY important
build_script:
- ps: >-
    Set-PSDebug -Trace 2

    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/francois-keith/testAppveyor/master/installAsAppveyorDependency.ps1'))

    git submodule update --init --recursive

    . ./.travis/functions.ps1

    setup_build

    ./.travis/dependencies/eigen-3.2.ps1

    install_dependencies

    build_project
test_script:
- ps: >-
    Set-PSDebug -Trace 2

    . ./.travis/functions.ps1

    test_project
